export const PERSIST_READY = 'PERSIST_READY'

export const FETCH_VIDEOSFROMDB_FETCHING = 'FETCH_VIDEOSFROMDB_FETCHING'
export const FETCH_VIDEOSFROMDB_ERROR = 'FETCH_VIDEOSFROMDB_ERROR'
export const FETCH_VIDEOSFROMDB_SUCCESS = 'FETCH_VIDEOSFROMDB_SUCCESS'

export const FETCH_EXECQUERYDB_FETCHING = 'FETCH_EXECQUERYDB_FETCHING'
export const FETCH_EXECQUERYDB_ERROR = 'FETCH_EXECQUERYDB_ERROR'
export const FETCH_EXECQUERYDB_SUCCESS = 'FETCH_EXECQUERYDB_SUCCESS'

export const FETCH_AUTOCOMPLETERESULTS_FETCHING = 'FETCH_AUTOCOMPLETERESULTS_FETCHING'
export const FETCH_AUTOCOMPLETERESULTS_ERROR = 'FETCH_AUTOCOMPLETERESULTS_ERROR'
export const FETCH_AUTOCOMPLETERESULTS_SUCCESS = 'FETCH_AUTOCOMPLETERESULTS_SUCCESS'

export const FETCH_SEARCHVIDEOS_FETCHING = 'FETCH_SEARCHVIDEOS_FETCHING'
export const FETCH_SEARCHVIDEOS_ERROR = 'FETCH_SEARCHVIDEOS_ERROR'
export const FETCH_SEARCHVIDEOS_SUCCESS = 'FETCH_SEARCHVIDEOS_SUCCESS'

export const DRAWER_TRIGGER = 'DRAWER_TRIGGER'

export const SET_NAVBARPROPS = 'SET_NAVBARPROPS'

export const SEARCH_TRIGGER = 'SEARCH_TRIGGER'

export const SET_SEARCHTEXT = 'SET_SEARCHTEXT'

export const SET_VIDEO_SHOW = 'SET_VIDEO_SHOW'
export const SET_VIDEO_STATE = 'SET_VIDEO_STATE'
export const SET_VIDEO_SHOW_AND_STATE = 'SET_VIDEO_SHOW_AND_STATE'

export const SET_ORIENTATION = 'SET_ORIENTATION'
export const INITIAL_ORIENTATION = 'INITIAL_ORIENTATION'

export const CHECK_HELPERS = 'CHECK_HELPERS'
export const TRIGGER_HELPER = 'TRIGGER_HELPER'